GET http://localhost:3000

###

GET http://localhost:3000/full-name

###

GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "age": 32
}